### ISSUE TITLE
NameError: name 'demande_remplissage_automatique' is not defined

### ISSUE THREAD

**Issue by ciroiriarte** [Aminata-Dev/PlaylistDeezerToSpotify#1]
Good afternoon!, 

Thanks for sharing the script, I just wanted to share that I found an issue trying to use it:

![image](https://user-images.githubusercontent.com/1750260/116010392-a8ee8180-a5ec-11eb-9614-448f8934a0c8.png)

Any hints?

**Comment by Aminata-Dev** [comment]
> Good afternoon!, 
> 
> 
> 
> Thanks for sharing the script, I just wanted to share that I found and issue trying to use it:
> 
> 
> 
> ![image](https://user-images.githubusercontent.com/1750260/116010392-a8ee8180-a5ec-11eb-9614-448f8934a0c8.png)
> 
> 
> 
> Any hints?

Good afternoon !
Thank you for pointing that out. I think I found the solution, but I can't test it now. Can you try to add :
``demande_remplissage_automatique = 'n'``
on line 42 ? If not, I will fix that tomorrow :).

**Comment by ciroiriarte** [comment]
Yup, I did something similar to make it work, but probably needs more care :)

```
--- PlaylistDeezerToSpotify.py-orig     2021-04-25 17:39:11.034352291 -0400
+++ PlaylistDeezerToSpotify.py  2021-04-25 17:40:10.574864471 -0400
@@ -47,6 +47,7 @@ if os.path.exists('informations_spotify_
             lignes_fichier = fichier.read()
             #car avec la méthode readlines, chaque str etait precede d'un \n, ce qui creait des conflit car il etait "invisible" :
             nom_utilisateur_spotify, id_client, mdp_client = lignes_fichier.split('\n')[0], lignes_fichier.split('\n')[1], lignes_fichier.split('\n')[2]
+demande_remplissage_automatique = 'n'
 if demande_remplissage_automatique != 'y': #Si l'utilisateur ne veut pas entrer ces informations automatiquement
     #Initialisation des données du compte spotify :
     nom_utilisateur_spotify = input("\nWhat is your Spotify username ? : ( https://www.spotify.com/ca-en/account/overview/?utm_source=play&utm_campaign=wwwredirect > Copy/Past Username )\n@> ")
```
