### ISSUE TITLE
400 songs limit?

### ISSUE THREAD

**Issue by ciroiriarte** [Aminata-Dev/PlaylistDeezerToSpotify#2]
Hello!, 

Is there a limit of 399 or 400 songs somewhere?. First try of a 453 songs list only imported 399, second test with ~700 songs only list 400 in the song list step before importing.

**Comment by ciroiriarte** [comment]
It seems to be a paging thing: https://stackoverflow.com/questions/22639745/deezer-api-get-more-than-400-songs-from-a-playlist

**Comment by Aminata-Dev** [comment]
> Hello!, 
> 
> 
> 
> Is there a limit of 399 or 400 songs somewhere?. First try of a 453 songs list only imported 399, second test with ~700 songs only list 400 in the song list step before importing.

**Fixed !**
It should work now. I had noticed this issue but couldn't find the solution in the Deezer documentation. Thanks for the link, it helped me a lot. You can also now see all the songs that were not found.
Have a nice day :)
